
sudo: required

language: php

services:
  - docker

branches:
  only:
  - master
  - develop

jobs:
  include:
    - stage: Docker Build And Push
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_OBDEV" -p="$DOCKER_PASSWORD_OBDEV";
            docker build -t $DOCKER_USERNAME_OBDEV/flz-wdp-v6-demo:master --build-arg env_1="$REMOTE_ADDR" .;
            docker images;
            docker push $DOCKER_USERNAME_OBDEV/flz-wdp-v6-demo:master;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME_OBDEV" -p="$DOCKER_PASSWORD_OBDEV";
            docker build -t $DOCKER_USERNAME_OBDEV/flz-wdp-v6-demo:dev .;
            docker images;
            docker push $DOCKER_USERNAME_OBDEV/flz-wdp-v6-demo:dev;
        fi'

    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh


notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - denis@flowzdigital.com
      - vinodbarot91@gmail.com
    on_success: always
    on_failure: always
