M©ÐZ<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:585;s:11:"post_author";s:1:"2";s:9:"post_date";s:19:"2018-02-15 05:33:41";s:13:"post_date_gmt";s:19:"2018-02-15 05:33:41";s:12:"post_content";s:7613:"[vc_row full_width="stretch_row" full_height="yes" equal_height="yes" content_placement="middle" css=".vc_custom_1518712304638{background-image: url(https://www.officebeacon.com/wp-content/uploads/2018/02/b7_01.png?id=594) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_column_text el_class="bannerext_lat"]<span style="color: #ffffff;">ABOUT US</span>[/vc_column_text][vc_column_text][echo-content-down-arrow id="temp-id" class="dwn_arrow" size="80" type="epda-icon-arrow-circle" animation_type="bounce-effect-1" color="1776C0" duration_time="50000" bouncing_speed="2000" move_to="3_row_col" scrolling="true" disable_bouncing="false" disable_duration="false" ][/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1518608389152{background-color: #22a1c4 !important;}"][vc_column][vc_column_text]
<p class="home_banner_text_oth" style="text-align: center;"><strong><span style="font-size: 24px;">Our People Power, Your Progress</span></strong></p>
<p class="home_banner_subtext" style="text-align: center;">Phenomenal Outsourcing To Grow Your Business</p>
[/vc_column_text][/vc_column][/vc_row][vc_row el_id="3_row_col"][vc_column width="1/3"][vc_single_image image="595" img_size="full" alignment="center"][vc_column_text]
<p class="about_head" style="text-align: center;">3 PRODUCTION CENTRES</p>
<p class="about_body" style="text-align: left;">With 1000s of workstations, our production centers span from India to the Philippines.</p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="5889" img_size="full" alignment="center"][vc_column_text]
<p class="about_head" style="text-align: center;">2500+ EMPLOYEES</p>
<p class="about_body" style="text-align: left;">Office Beacon offers a huge range of talented individuals.Â  If you don't see a service listed, just ask us!</p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="597" img_size="full" alignment="center"][vc_column_text]
<p class="about_head" style="text-align: center;">4500+ CLIENTS</p>
<p class="about_body" style="text-align: left;">Our clientele ranges from start-ups to Fortune 100 clients. We service clients from over 15 countries.</p>
[/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row_content" equal_height="yes" content_placement="middle"][vc_column width="1/2" el_class="about_company_image" css=".vc_custom_1518675216777{background-image: url(https://www.officebeacon.com/wp-content/uploads/2018/02/IMG_9573.jpg?id=598) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column][vc_column width="1/2" css=".vc_custom_1518712584263{padding-top: 50px !important;padding-bottom: 100px !important;background-color: #616161 !important;}"][vc_column_text]
<p class="about_company_text_head" style="text-align: left;">OUR MISSION</p>
<p class="about_company_text_body" style="text-align: left;">"Office Beacon creates value for businesses by providing significant competitive advantages. Your growth will create opportunities for our employees and growth for all. "</p>
<span style="color: #ffffff;">PRANAV DALAL, CHIEF DISRUPTION OFFICER</span>[/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" css=".vc_custom_1518712803389{background-color: #eeeeee !important;}"][vc_column][vc_column_text css=".vc_custom_1521389995000{margin-top: 30px !important;}"]
<p style="text-align: center;"><span class="timeline_head">A Journey of Growth</span>
<span class="timeline_body">The Office Beacon Timeline</span></p>
[/vc_column_text][vc_column_text el_class="the_timeliners"][wpex_timeline style="" alignment="center" posttype="wp-timeline" count="10" posts_per_page="3" ids="" cat="Facebook" tag="" taxonomy="" order="ASC" orderby="date" meta_key="" start_label="" end_label="" show_media="1" animations="" show_history="0" full_content="0" filter_cat="0" feature_label="0" hide_img="0" lightbox="0" infinite="0" class=""][/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row_content" equal_height="yes" content_placement="middle" el_class="teamings"][vc_column][vc_column_text]
<p style="text-align: center;"><span class="team_head">Our Leadership Team</span></p>
[/vc_column_text][vc_column_text el_class="team1"][team id="606"][/vc_column_text][vc_column_text el_class="team1"][team id="5951"][/vc_column_text][vc_column_text el_class="team1"][team id="612"][/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1516716223007{padding-top: 50px !important;padding-bottom: 50px !important;background-image: url(https://www.officebeacon.com/wp-content/uploads/2018/01/OB-LandingPage-ACCOUNTING_19.png?id=311) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_column_text]
<p class="savings_text" style="text-align: center; line-height: 35px;"><span style="font-size: 30px; color: #ffffff;">Are You Ready to Start Saving ? </span></p>
[/vc_column_text][vc_btn title="TRY OUR SAVINGS CALCULATOR" style="classic" color="default" size="lg" align="center" el_class="start_button" link="url:https%3A%2F%2Fwww.officebeacon.com%2Froi-calculator%2F|||"][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1519047463655{margin-top: 30px !important;background-color: #22a1c4 !important;}" el_class="counter_row2"][vc_column][vc_row_inner][vc_column_inner width="1/3"][vc_single_image image="316" alignment="center"][vc_btn title="NUMBER OF EMPLOYEES" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="color: #ffffff; font-size: 34px;">2500+</span></strong></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="317" alignment="center"][vc_btn title="PRODUCTION CENTERS" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="font-size: 30px; color: #ffffff;">3</span></strong></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="318" alignment="center"][vc_btn title="NUMBER OF CLIENTS" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="font-size: 30px; color: #ffffff;">4500+</span></strong></p>
[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="countries_row"][vc_column_inner][vc_column_text css_animation="none" css=".vc_custom_1518595653816{padding-bottom: 20px !important;}"]

<hr class="hor_line" />

<h4 style="text-align: right;"><span class="foot1" style="color: #ffffff; float: left; width: 37%; line-height: 24px;">We Are Global</span></h4>
<ul class="list-horizontal" style="float: left; width: 56%; text-align: center; display: inline-flex;">
 	<li><span class="foot2" style="color: #d6d2d2;">USA</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Canada</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Australia/New Zealand</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Phillipines</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">India</span></li>
</ul>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]";s:10:"post_title";s:8:"About Us";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:6:"closed";s:11:"ping_status";s:6:"closed";s:13:"post_password";s:0:"";s:9:"post_name";s:8:"about-us";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2018-03-19 14:21:09";s:17:"post_modified_gmt";s:19:"2018-03-19 14:21:09";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:41:"https://www.officebeacon.com/?page_id=585";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}