M©ÐZ<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:5551;s:11:"post_author";s:1:"2";s:9:"post_date";s:19:"2018-02-15 10:45:30";s:13:"post_date_gmt";s:19:"2018-02-15 10:45:30";s:12:"post_content";s:8757:"[vc_row full_width="stretch_row" full_height="yes" equal_height="yes" content_placement="middle" css=".vc_custom_1518688664319{background-image: url(https://www.officebeacon.com/wp-content/uploads/2018/02/b12_01.png?id=5532) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_column_text el_class="bannerext_lat"]<span style="color: #ffffff;">SERVICES</span>[/vc_column_text][vc_column_text][echo-content-down-arrow id="temp-id" class="dwn_arrow" size="80" type="epda-icon-arrow-circle" animation_type="bounce-effect-1" color="1776C0" duration_time="50000" bouncing_speed="2000" move_to="serv_row_all" scrolling="true" disable_bouncing="false" disable_duration="false" ][/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1518608389152{background-color: #22a1c4 !important;}"][vc_column][vc_column_text]
<p class="home_banner_text_oth" style="text-align: center;"><strong><span style="font-size: 24px;">Business Services</span></strong></p>
<p class="home_banner_subtext" style="text-align: center;">That Help You Grow</p>
[/vc_column_text][/vc_column][/vc_row][vc_row el_id="serv_row_all"][vc_column width="1/3"][vc_single_image image="5555" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/lead-generation-representatives/" el_class="acc_img"][vc_single_image image="5556" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/lead-generation-representatives/"][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/lead-generation-representatives/"><span class="service_header">LEAD GENERATION REPS</span></a>
<a href="https://www.officebeacon.com/lead-generation-representatives/"><span class="service_header_body">Warm leads sent directly to your inbox</span></a></p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="5822" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/graphic-artist/" label=""][vc_single_image image="5563" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/graphic-artist/" label=""][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/graphic-artist/"><span class="service_header">GRAPHIC ARTISTS</span></a>
<a href="https://www.officebeacon.com/graphic-artist/"><span class="service_header_body">Print, Digital and 3D</span></a></p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="5823" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/order-management/"][vc_single_image image="5565" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/order-management/"][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/order-management/"><span class="service_header">ORDER MANAGEMENT</span></a>
<a href="https://www.officebeacon.com/order-management/"><span class="service_header_body">Order Receipt to Fulfillment</span></a></p>
[/vc_column_text][/vc_column][/vc_row][vc_row][vc_column width="1/3"][vc_single_image image="5827" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/customer-service-representatives/"][vc_single_image image="5569" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/customer-service-representatives/"][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/customer-service-representatives/"><span class="service_header">CUSTOMER SERVICE REPS</span></a>
<a href="https://www.officebeacon.com/customer-service-representatives/"><span class="service_header_body">Inbound/Outbound/Virtual Assistants</span></a></p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="5828" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/accounting/"][vc_single_image image="5571" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/accounting/"][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/accounting/"><span class="service_header">ACCOUNTING</span></a>
<a href="https://www.officebeacon.com/accounting/"><span class="service_header_body">Journal Entries, Reporting, Analysis</span></a></p>
[/vc_column_text][/vc_column][vc_column width="1/3"][vc_single_image image="5829" img_size="full" alignment="center" onclick="custom_link" link="https://www.officebeacon.com/video-editors/"][vc_single_image image="5573" alignment="center" onclick="custom_link" el_class="service_mid_image" link="https://www.officebeacon.com/video-editors/"][vc_column_text el_class="service_mid_text"]
<p style="text-align: center;"><a href="https://www.officebeacon.com/video-editors/"><span class="service_header">VIDEO EDITING</span></a>
<a href="https://www.officebeacon.com/video-editors/"><span class="service_header_body">Full Editing &amp; Motion Graphics</span></a></p>
[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1518693698502{margin-top: 30px !important;}"][vc_column][vc_column_text]
<p class="service_partner" style="text-align: center;">Let us supply the coverage when and where you need it most</p>

<h3 class="service_partner_head" style="text-align: center;">Partner with Office Beacon</h3>
[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1516716223007{padding-top: 50px !important;padding-bottom: 50px !important;background-image: url(https://www.officebeacon.com/wp-content/uploads/2018/01/OB-LandingPage-ACCOUNTING_19.png?id=311) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_column_text]
<p class="savings_text" style="text-align: center; line-height: 35px;"><span style="font-size: 30px; color: #ffffff;">Are You Ready to Start Saving ? </span></p>
[/vc_column_text][vc_btn title="TRY OUR SAVINGS CALCULATOR" style="classic" color="default" size="lg" align="center" el_class="start_button" link="url:https%3A%2F%2Fwww.officebeacon.com%2Froi-calculator%2F|||"][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1519048285280{margin-top: 30px !important;background-color: #22a1c4 !important;}" el_class="counter_row2"][vc_column][vc_row_inner][vc_column_inner width="1/3"][vc_single_image image="316" alignment="center"][vc_btn title="NUMBER OF EMPLOYEES" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="color: #ffffff; font-size: 34px;">2500+</span></strong></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="317" alignment="center"][vc_btn title="PRODUCTION CENTERS" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="font-size: 30px; color: #ffffff;">3</span></strong></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="318" alignment="center"][vc_btn title="NUMBER OF CLIENTS" style="flat" shape="square" color="info" align="center"][vc_column_text]
<p class="save_numbers" style="text-align: center;"><strong><span class="save_numbers" style="font-size: 30px; color: #ffffff;">4500+</span></strong></p>
[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="countries_row"][vc_column_inner][vc_column_text css_animation="none" css=".vc_custom_1518595653816{padding-bottom: 20px !important;}"]

<hr class="hor_line" />

<h4 style="text-align: right;"><span class="foot1" style="color: #ffffff; float: left; width: 37%; line-height: 24px;">We Are Global</span></h4>
<ul class="list-horizontal" style="float: left; width: 56%; text-align: center; display: inline-flex;">
 	<li><span class="foot2" style="color: #d6d2d2;">USA</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Canada</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Australia/New Zealand</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">Phillipines</span></li>
 	<li><span class="foot2" style="color: #d6d2d2;">India</span></li>
</ul>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]";s:10:"post_title";s:8:"Services";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:6:"closed";s:11:"ping_status";s:6:"closed";s:13:"post_password";s:0:"";s:9:"post_name";s:8:"services";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2018-04-09 10:37:18";s:17:"post_modified_gmt";s:19:"2018-04-09 10:37:18";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:42:"https://www.officebeacon.com/?page_id=5551";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}